Repository fjeos/5rmi, pull requests merged in 2024-08, with the labels that each got.

#17 [Feature] Search Posts By Title
  src/main/java/com/ormi5/movieblog/comment/CommentDto.java
  src/main/java/com/ormi5/movieblog/commentcontroller/CommentController.java
  src/main/java/com/ormi5/movieblog/commentcontroller/CommentService.java
  src/main/java/com/ormi5/movieblog/post/Post.java
  src/main/java/com/ormi5/movieblog/post/PostDto.java
  src/main/java/com/ormi5/movieblog/postcontroller/PostController.java
  src/main/java/com/ormi5/movieblog/postcontroller/PostRepository.java
  src/main/java/com/ormi5/movieblog/postcontroller/PostService.java
Labels: enhancement

#18 Feature/get profile
  src/main/java/com/ormi5/movieblog/post/ProfilePostResponseDto.java
  src/main/java/com/ormi5/movieblog/postcontroller/PostService.java
  src/main/java/com/ormi5/movieblog/user/ProfileResponseDto.java
  src/main/java/com/ormi5/movieblog/usercontroller/UserController.java
  src/main/java/com/ormi5/movieblog/usercontroller/UserService.java
Labels: enhancement

#20 Feature/front_view_post
  src/main/java/com/ormi5/movieblog/post/Post.java
  src/main/java/com/ormi5/movieblog/postcontroller/PostController.java
  src/main/java/com/ormi5/movieblog/postcontroller/PostService.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/post/detail.html
Labels: enhancement

#21 [Feat] 게시글 수정 화면 개발
  src/main/java/com/ormi5/movieblog/post/Post.java
  src/main/java/com/ormi5/movieblog/post/PostUpdateDto.java
  src/main/java/com/ormi5/movieblog/postcontroller/PostController.java
  src/main/java/com/ormi5/movieblog/postcontroller/PostService.java
  src/main/resources/templates/post/edit.html
Labels: enhancement

#22 [Fix] detail.html에서 post.id 를 post.postId 로 변경
  src/main/resources/templates/post/detail.html
Labels: bug

#25 Feature/like_dislike
  src/main/java/com/ormi5/movieblog/comment/Comment.java
  src/main/java/com/ormi5/movieblog/commentcontroller/CommentController.java
  src/main/java/com/ormi5/movieblog/commentcontroller/CommentRepository.java
  src/main/java/com/ormi5/movieblog/commentcontroller/CommentService.java
  src/main/java/com/ormi5/movieblog/post/Post.java
  src/main/java/com/ormi5/movieblog/postcontroller/PostController.java
  src/main/java/com/ormi5/movieblog/postcontroller/PostService.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/post/detail.html
Labels: enhancement

#36 [Fix] 댓글 수정 오류
  src/main/java/com/ormi5/movieblog/commentcontroller/CommentController.java
  src/main/resources/templates/comment/edit_comment.html
  src/main/resources/templates/post/detail.html
Labels: enhancement

#45 [Fix] Cannot access own private posts, cannot change post visibility.
  src/main/java/com/ormi5/movieblog/post/Post.java
  src/main/java/com/ormi5/movieblog/postcontroller/PostController.java
  src/main/resources/templates/post/edit.html
Labels: bug, enhancement

#48 [Fix] Fix comment bugs
  src/main/java/com/ormi5/movieblog/commentcontroller/CommentController.java
  src/main/java/com/ormi5/movieblog/postcontroller/PostController.java
  src/main/resources/templates/post/detail.html
Labels: bug, enhancement

#52 featuer/member_leave
  src/main/java/com/ormi5/movieblog/usercontroller/UserController.java
  src/main/java/com/ormi5/movieblog/usercontroller/UserService.java
  src/main/resources/templates/user/user.html
Labels: enhancement

#53 [Style] CSS 적용
  src/main/java/com/ormi5/movieblog/WebSecurityConfig.java
  src/main/java/com/ormi5/movieblog/announcementcontroller/AnnouncementController.java
  src/main/java/com/ormi5/movieblog/banhammer/BanHammerController.java
  src/main/java/com/ormi5/movieblog/commentcontroller/CommentController.java
  src/main/java/com/ormi5/movieblog/loginservice/LoginController.java
  src/main/java/com/ormi5/movieblog/postboard/PostBoardController.java
  src/main/java/com/ormi5/movieblog/postcontroller/PostController.java
  src/main/java/com/ormi5/movieblog/user/ProfileResponseDto.java
  src/main/java/com/ormi5/movieblog/usercontroller/UserService.java
  src/main/resources/static/css/style.css
  src/main/resources/static/mainpage.css
  src/main/resources/static/style.css
  src/main/resources/templates/admin/admin.html
  src/main/resources/templates/announcement/detail.html
  src/main/resources/templates/announcement/edit.html
  src/main/resources/templates/announcement/newannouncement.html
  src/main/resources/templates/comment/add_comment.html
  src/main/resources/templates/comment/edit_comment.html
  src/main/resources/templates/home.html
  src/main/resources/templates/layout/footer.html
  src/main/resources/templates/layout/nav.html
  src/main/resources/templates/login/banned.html
  src/main/resources/templates/post/detail.html
  src/main/resources/templates/post/edit.html
  src/main/resources/templates/post/newpost.html
  src/main/resources/templates/postboard.html
  src/main/resources/templates/user/user.html
Labels: enhancement
